--!strict
--
-- CONSTANTS
--
local PINK_KEYWORDS = {
	"function" ,               
	"return"   ,
	"end"      ,
	"if"       ,
	"not"      ,
	"or"       ,
	"and"      ,
	"then"     ,
	"else"     ,
	"elseif"   ,
	"for"      ,
	"in"       ,
	"while"    ,
	"do"       ,
	"repeat"   ,
	"until"    ,
	"break"    ,
	"continue" ,
	"local"    ,
	"export"   ,
	"type"     ,
}
--
-- RETURN VALUE
--
return PINK_KEYWORDS