--!strict
--
-- CONSTANTS
--
local PINK_KEYWORDS = {
	["function"] = true,               
	["return"]   = true,
	["end"]      = true,
	["if"]       = true,
	["not"]      = true,
	["or"]       = true,
	["and"]      = true,
	["then"]     = true,
	["else"]     = true,
	["elseif"]   = true,
	["for"]      = true,
	["in"]       = true,
	["while"]    = true,
	["do"]       = true,
	["repeat"]   = true,
	["until"]    = true,
	["break"]    = true,
	["continue"] = true,
	["local"]    = true,
	["export"]   = true,
	["type"]     = true,
}
--
-- RETURN VALUE
--
return PINK_KEYWORDS