--!strict
--
-- CONSTANTS
--
local YELLOW_KEYWORDS = {
	"Rect"            ,                                                                 
	"Region3"         ,
	"Instance"        ,
	"Model"           ,
	"Part"            ,
	"BasePart"        ,
	"ScreenGui"       ,
	"Frame"           ,
	"TextLabel"       ,
	"TextButton"      ,
	"ImageButton"     ,
	"ScrollingFrame"  ,
	"UIListLayout"    ,
	"UIGridLayout"    ,
	"UICorner"        ,
	"UIPadding"       ,
	"UIScale"         ,
	"UIStroke"        ,
	"UIGradient"      ,
	"CanvasGroup"     ,
	"ViewportFrame"   ,
	"SurfaceGui"      ,
}
--
-- RETURN VALUE
--
return YELLOW_KEYWORDS